language: python
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install --deploy --dev
before_script:
  - curl https://www.bde.enseeiht.fr/~saurelg/11_keys.asc | gpg --import
script:
  - ./manage.py migrate
  - coverage run manage.py test
  - flake8 .
  - yapf -dr .
  - safety check
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=pgp_tables"
after_success:
  - coveralls
