# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgp_tables', '0002_null_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='algorithm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='creation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
