# Generated by Django 2.0 on 2017-12-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgp_tables', '0003_key_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
